### ISSUE TITLE
SDA und SCL Pins vertauschen

### ISSUE THREAD

**Issue by janv** [rancilio-pid/clevercoffee-hardware#11]
ich baue gerade das Projekt auf Basis des 1.2 minimal ESP32 boards zusammen und mir fällt auf dass die Pinbelegung auf dem Board für I2C `SCL SDA VCC GND` ist, die Reihenfolge der Pins auf dem Display board allerdings `SDA SCL VCC GND`.

Wenn ich die mit einem Flachkabel verbinden will muss ich irgendwo SDA und SCL kreuzen, es wäre vielleicht geschickter, wenn die schon in der richtigen reihenfolge vom Board kämen

**Comment by fiendie** [comment]
Die Belegung ist eigentlich nicht spezifisch für das Display gedacht gewesen (man kann an dem Bus ja auch andere Peripherie betreiben) und je nachdem, welches der beiden Displays du verwendest (1,3" oder 0,96"), sind VCC und GND vertauscht. Also irgendwer muss immer ein paar Drähte Kreuzen :)
Außerdem müssen mit der Belegung die Leiterbahnen auf dem PCB nicht gekreuzt werden.
